apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student-container
        image: mohdazhar32/student-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  type: NodePort
  selector:
    app: student
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
